### ISSUE TITLE
非常好，简单易看，适合我们新手村

### ISSUE THREAD

**Issue by jiaojiren** [JohnnyMu/vue-blog-master#3]
不知道2020年了，里面的某些技术会不会已经废弃了的

**Comment by jiaojiren** [comment]
想问问大佬是怎么进行模块化开发的，比如怎么建立config 、build等等的文件夹

**Comment by jiaojiren** [comment]
大佬有没有博客文章关于对这个项目的讲解的，想学习

**Comment by RichDavidMu** [comment]
感谢认可，模块化建设看一下webpack文档以及这个项目中使用的vue-cli的文档，详解最近没时间写，可以先用postman测试一下后端的接口，再去看前端部分，从入口文件开始顺着依赖关系往下看。
